languageCode: es-ES
title: WeLoveHMIS
theme: PaperMod
paginate: 10

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

params:
  label:
    text: "WeLoveHMIS"
    icon: /apple-touch-icon.png
    iconHeight: 35
  ShowReadingTime: true
  ShowToc: true
  disableSpecial1stPost: true
  TocOpen: true

taxonomies:
  tag: tags
  author: authors

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: contact
      name: "Contacto"
      url: "/en/contact/"
      weight: 10
